-- 備份時間: 2026-01-20 10:49:46.361617
-- 原始表格: bronze.common_hr_employee

CREATE TABLE bronze.common_hr_employee
(
    `EmpCode` String,
    `EmpName` Nullable(String),
    `DisplayName` Nullable(String),
    `UnicodeName` Nullable(String),
    `EnglishName` Nullable(String),
    `FirstName` Nullable(String),
    `MiddleName` Nullable(String),
    `LastName` Nullable(String),
    `ADAccount` Nullable(String),
    `ADDomain` Nullable(String),
    `TerminateDate` Nullable(DateTime64(3)),
    `Email` Nullable(String),
    `ExtNo` Nullable(String),
    `DeptCode` Nullable(String),
    `DeptCodeLname` Nullable(String),
    `DeptCodeEname` Nullable(String),
    `CostCenterCode` Nullable(String),
    `CostCenterLname` Nullable(String),
    `SuperiorDeptCode` Nullable(String),
    `SuperiorDeptLname` Nullable(String),
    `SuperiorDeptEname` Nullable(String),
    `Supervisor` Nullable(String),
    `FactoryCode` Nullable(String),
    `FactoryLname` Nullable(String),
    `FactoryEname` Nullable(String),
    `BGID` Nullable(Int32),
    `BGShortName` Nullable(String),
    `BUID` Nullable(Int32),
    `BUShortName` Nullable(String),
    `CompanyCode` Nullable(String),
    `CompanyLname` Nullable(String),
    `CompanyEname` Nullable(String),
    `SAPCompanyCode` Nullable(String),
    `AreaID` Nullable(String),
    `AreaLname` Nullable(String),
    `AreaEname` Nullable(String),
    `GenderID` Nullable(UInt8),
    `GenderLname` Nullable(String),
    `GenderEname` Nullable(String),
    `Shift` Nullable(String),
    `OrgUnitCode` Nullable(String),
    `OrgUnitLname` Nullable(String),
    `OrgUnitEname` Nullable(String),
    `OrgUnitMgrEmpNo` Nullable(String),
    `JobFamilyCode` Nullable(String),
    `JobFamilyName` Nullable(String),
    `JobFamilyEName` Nullable(String),
    `DeptEmpCode` Nullable(String),
    `DeptEmpName` Nullable(String),
    `CostCenterEname` Nullable(String),
    `ModifyDate` DateTime64(6),
    `JobCode` Nullable(String)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192;
