-- ============================================
-- APP_SRV_BPM - Flowable 完整 Schema
-- ============================================

USE APP_SRV_BPM;
GO

-- 1. ACT_HI_PROCINST - 流程實例歷史 (21 欄)
CREATE TABLE ACT_HI_PROCINST (
    ID_ NVARCHAR(64) NOT NULL PRIMARY KEY,
    REV_ INT NULL,
    PROC_INST_ID_ NVARCHAR(64) NOT NULL,
    BUSINESS_KEY_ NVARCHAR(255) NULL,
    PROC_DEF_ID_ NVARCHAR(64) NOT NULL,
    START_TIME_ DATETIME NOT NULL,
    END_TIME_ DATETIME NULL,
    DURATION_ NUMERIC(19,0) NULL,
    START_USER_ID_ NVARCHAR(255) NULL,
    START_ACT_ID_ NVARCHAR(255) NULL,
    END_ACT_ID_ NVARCHAR(255) NULL,
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR(64) NULL,
    DELETE_REASON_ NVARCHAR(4000) NULL,
    TENANT_ID_ NVARCHAR(255) NULL,
    NAME_ NVARCHAR(255) NULL,
    CALLBACK_ID_ NVARCHAR(255) NULL,
    CALLBACK_TYPE_ NVARCHAR(255) NULL,
    REFERENCE_ID_ NVARCHAR(255) NULL,
    REFERENCE_TYPE_ NVARCHAR(255) NULL,
    PROPAGATED_STAGE_INST_ID_ NVARCHAR(255) NULL,
    BUSINESS_STATUS_ NVARCHAR(255) NULL
);
GO

-- 2. ACT_HI_TASKINST - 任務實例歷史 (28 欄)
CREATE TABLE ACT_HI_TASKINST (
    ID_ NVARCHAR(64) NOT NULL PRIMARY KEY,
    REV_ INT NULL,
    PROC_DEF_ID_ NVARCHAR(64) NULL,
    TASK_DEF_ID_ NVARCHAR(64) NULL,
    TASK_DEF_KEY_ NVARCHAR(255) NULL,
    PROC_INST_ID_ NVARCHAR(64) NULL,
    EXECUTION_ID_ NVARCHAR(64) NULL,
    SCOPE_ID_ NVARCHAR(255) NULL,
    SUB_SCOPE_ID_ NVARCHAR(255) NULL,
    SCOPE_TYPE_ NVARCHAR(255) NULL,
    SCOPE_DEFINITION_ID_ NVARCHAR(255) NULL,
    PROPAGATED_STAGE_INST_ID_ NVARCHAR(255) NULL,
    NAME_ NVARCHAR(255) NULL,
    PARENT_TASK_ID_ NVARCHAR(64) NULL,
    DESCRIPTION_ NVARCHAR(4000) NULL,
    OWNER_ NVARCHAR(255) NULL,
    ASSIGNEE_ NVARCHAR(255) NULL,
    START_TIME_ DATETIME NOT NULL,
    CLAIM_TIME_ DATETIME NULL,
    END_TIME_ DATETIME NULL,
    DURATION_ NUMERIC(19,0) NULL,
    DELETE_REASON_ NVARCHAR(4000) NULL,
    PRIORITY_ INT NULL,
    DUE_DATE_ DATETIME NULL,
    FORM_KEY_ NVARCHAR(255) NULL,
    CATEGORY_ NVARCHAR(255) NULL,
    TENANT_ID_ NVARCHAR(255) NULL,
    LAST_UPDATED_TIME_ DATETIME2 NULL
);
GO


-- 3. ACT_HI_IDENTITYLINK - 任務參與者歷史 (11 欄)
CREATE TABLE ACT_HI_IDENTITYLINK (
    ID_ NVARCHAR(64) NOT NULL PRIMARY KEY,
    GROUP_ID_ NVARCHAR(255) NULL,
    TYPE_ NVARCHAR(255) NULL,
    USER_ID_ NVARCHAR(255) NULL,
    TASK_ID_ NVARCHAR(64) NULL,
    CREATE_TIME_ DATETIME NULL,
    PROC_INST_ID_ NVARCHAR(64) NULL,
    SCOPE_ID_ NVARCHAR(255) NULL,
    SUB_SCOPE_ID_ NVARCHAR(255) NULL,
    SCOPE_TYPE_ NVARCHAR(255) NULL,
    SCOPE_DEFINITION_ID_ NVARCHAR(255) NULL
);
GO

-- 4. ACT_HI_VARINST - 流程變數歷史 (18 欄)
CREATE TABLE ACT_HI_VARINST (
    ID_ NVARCHAR(64) NOT NULL PRIMARY KEY,
    REV_ INT NULL,
    PROC_INST_ID_ NVARCHAR(64) NULL,
    EXECUTION_ID_ NVARCHAR(64) NULL,
    TASK_ID_ NVARCHAR(64) NULL,
    NAME_ NVARCHAR(255) NOT NULL,
    VAR_TYPE_ NVARCHAR(100) NULL,
    SCOPE_ID_ NVARCHAR(255) NULL,
    SUB_SCOPE_ID_ NVARCHAR(255) NULL,
    SCOPE_TYPE_ NVARCHAR(255) NULL,
    BYTEARRAY_ID_ NVARCHAR(64) NULL,
    DOUBLE_ FLOAT NULL,
    LONG_ NUMERIC(19,0) NULL,
    TEXT_ NVARCHAR(4000) NULL,
    TEXT2_ NVARCHAR(4000) NULL,
    CREATE_TIME_ DATETIME NULL,
    LAST_UPDATED_TIME_ DATETIME2 NULL,
    META_INFO_ NVARCHAR(4000) NULL
);
GO

-- 5. ACT_RE_PROCDEF - 流程定義 (18 欄)
CREATE TABLE ACT_RE_PROCDEF (
    ID_ NVARCHAR(64) NOT NULL PRIMARY KEY,
    REV_ INT NULL,
    CATEGORY_ NVARCHAR(255) NULL,
    NAME_ NVARCHAR(255) NULL,
    KEY_ NVARCHAR(255) NOT NULL,
    VERSION_ INT NOT NULL,
    DEPLOYMENT_ID_ NVARCHAR(64) NULL,
    RESOURCE_NAME_ NVARCHAR(4000) NULL,
    DGRM_RESOURCE_NAME_ NVARCHAR(4000) NULL,
    DESCRIPTION_ NVARCHAR(4000) NULL,
    HAS_START_FORM_KEY_ TINYINT NULL,
    HAS_GRAPHICAL_NOTATION_ TINYINT NULL,
    SUSPENSION_STATE_ TINYINT NULL,
    TENANT_ID_ NVARCHAR(255) NULL,
    DERIVED_FROM_ NVARCHAR(64) NULL,
    DERIVED_FROM_ROOT_ NVARCHAR(64) NULL,
    DERIVED_VERSION_ INT NOT NULL,
    ENGINE_VERSION_ NVARCHAR(255) NULL
);
GO
