[MSSQL_DSN]
Driver = ODBC Driver 18 for SQL Server
Server = WJOAUATDB01S.delta.corp,65000
TrustServerCertificate = yes
Encrypt = no
LoginTimeout = 30

# Username and Password are provided dynamically in the Python connection string.
# Example: DSN=MSSQL_DSN;Database=APP_SRV_BPM;Uid=APP_SRV_BPM;Pwd=YOUR_PASSWORD;MARS_Connection=yes
